version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: brightup_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: brightup
    ports:
      - "3306:3306"
    volumes:
      - ./database/brightup_schema.sql:/docker-entrypoint-initdb.d/brightup_schema.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: brightup_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root1234
      DB_NAME: brightup
      SECRET_KEY: brightup_super_secret_2024_xkq93
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440

  frontend:
    build: ./frontend
    container_name: brightup_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: